# -*- coding: utf-8 -*-
"""NewtonRoot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwePbgd6PTKesxREcP0k_r2XqxS_17a4
"""

import numpy as np
import matplotlib.pyplot as plt


#comenzamos definiendo la funcion a evaluar

def f(x):
  return np.sin(1/x)

#Definimos su derivada

def df(x):
  return -(np.cos(1/x)/x**2)

#tomemos un primer valor de aproximación

x_0 = [0.4]

epsilon = 0.0000003 #Definimos el error aceptado

if len(x_0) <= 2:
  x_0.append(x_0[0]-(f(x_0[0])/df(x_0[0])))

while abs(x_0[-1]-x_0[-2]) > epsilon:
  x_0.append(x_0[-1]-(f(x_0[-1])/df(x_0[-1])))

print(x_0)