# -*- coding: utf-8 -*-
"""pi_montecarlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Q44m5KpEwza6-EOnZRnjucvrwjMad_v
"""

import random
import numpy as np
import matplotlib.pyplot as plt
import math

#Definimos una función a la cual le asignaremos una cantidad de números aleatorios y este devuelve un valor de pi
def pi(n):
  total_puntos = 0
  puntos_circulo = 0
  for i in range(0, n):
    x = random.random()
    y = random.random()
    if x**2 + y**2 < 1:
      puntos_circulo += 1
    total_puntos += 1
  return 4 * puntos_circulo / total_puntos

#Probemos su comportamiento para bajos valores de N
N = list(range(10, 10000, 100))
pi_N = [pi(j) for j in N]

plt.plot(N, pi_N)
plt.ylabel("pi(N)")
plt.xlabel("N")
plt.show()

#comportamiento en el infinito
N_large = list(range(1000, 1000000, 1000))
pi_N_large = [pi(j) for j in N_large]

plt.plot(N_large, pi_N_large)
plt.ylabel("pi(N)")
plt.xlabel("N")
plt.show()

#Definimos una función que nos aplique regresión exponencial a un conjunto de datos

def regresion_algebraica(x, y):
  Y = np.log(y)
  X = np.log(x)
  n = len(X)
  sum_x = sum(X)
  sum_y = sum(Y)
  sum_xy = sum([X[i]*Y[i] for i in range(n)])
  sum_x2 = sum([X[i]**2 for i in range(n)])
  a = (sum_y*sum_x2 - sum_x*sum_xy) / (n*sum_x2 - sum_x**2)
  b = (n*sum_xy - sum_x*sum_y) / (n*sum_x2 - sum_x**2)
  return a, b

#Definimos una función que nos calcule el coeficiente de determinación

def coeficiente_determinacion_algebraico(x, y, a, b):
    n = len(x)
    # 1. Calculamos el promedio de los datos reales de 'y'
    y_med = sum(y) / n

    deviation_y_pred = 0
    deviation_y = 0

    for i in range(n):
      # 2. Evaluamos usando la función exponencial REAL reconstruida: y = e^a * e^(b*x)
      #    que es equivalente a: np.exp(a + b * x[i])
      y_predicha = np.exp(a) * (x[i] ** b)

      # 3. Sumamos los residuos al cuadrado en la escala real
      deviation_y_pred += (y[i] - y_predicha) ** 2
      deviation_y += (y[i] - y_med) ** 2

    return 1 - (deviation_y_pred / deviation_y)

N = list(range(10, 100000, 100))
pi_N = [pi(j) for j in N]

# pi_values_tested will será el almacenamiento de los pi evaluados
# C_Determinacion_calculated será el valor de los respectivos coeficientes de determinación
pi_values_tested = []
C_Determinacion_calculated = []

epsilon = 0.0001 #Los pasos que daremos en busca del pi_00 acertado

pi_current = 3.0 #Valor inicial de pi

# Loop para generar candidatos de pi y calcular su R2
while pi_current < 3.2:
  pi_values_tested.append(pi_current) # Guardar el candidato actual de pi
  f_N = [np.abs(pi_values_tested[-1] - k) for k in pi_N] # Calcular f_00 para el actual candidato
  a, b = regresion_algebraica(N, f_N)
  r_squared = coeficiente_determinacion_algebraico(N, f_N, a, b)
  C_Determinacion_calculated.append(r_squared) # Guardar el R2

  pi_current = pi_values_tested[-1] + epsilon # Moverse al siguiente candidato de pi

# Ahora, los valores de pi y de los coeficientes están en una lista

#pi_real y C_Determinación_real van a ser los valores donde el R2 es maximo
pi_real = pi_values_tested[0]
C_Determinación_real = C_Determinacion_calculated[0]

pi_noreal = pi_values_tested[0]
C_Determinación_noreal = C_Determinacion_calculated[0]

#Iteramos para hallar el valor de pi con el coeficiente mayor
for i in range(len(C_Determinacion_calculated)):
  if C_Determinacion_calculated[i] > C_Determinación_real:
    pi_real = pi_values_tested[i]
    C_Determinación_real = C_Determinacion_calculated[i]

for i in range(len(C_Determinacion_calculated)):
  if C_Determinacion_calculated[i] < C_Determinación_noreal:
    pi_noreal = pi_values_tested[i]

#Ya teniendo el valor al cual converge la serie, calculemos el error en funcion de N y los parametros de su respectiva regresión
error = [np.abs(pi_real - k) for k in pi_N]
a, b = regresion_algebraica(N, error)


print("b = ", b)
print("pi_max = ", pi_real)
print("R2 max = ", C_Determinación_real)
print("pi_min = ", pi_noreal)
print("R2 min = ", C_Determinación_noreal)


plt.plot(pi_values_tested, C_Determinacion_calculated)
plt.xlabel("pi")
plt.ylabel("R2")
plt.legend()
plt.show()